# Basics
site_name: Starry-Tutorial-Book
repo_url: https://github.com/Azure-stars/Starry-Tutorial-Book
repo_name: Starry-Tutorial-Book

theme:
  name: material
  language: zh
  custom_dir: theme/
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - primary: white
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format

# Contents
nav:
  - 欢迎来到 Starry-Tutorial-Book:
    - index.md
    - Starry 支持情况: ./intro/support.md

  - 快速上手:
    - setup/index.md
    - 环境配置: setup/env.md
    - 运行基本应用: setup/basic.md
    - 运行 OS 比赛测例: setup/oscomp.md
    - Starry 的自定义配置: setup/customization.md
    - 更多复杂应用: setup/applications.md

  - 架构设计:
    - implementation/index.md
    - 整体架构: implementation/architecture.md
    - 启动与初始化: implementation/boot.md
    - 宏内核结构设计: implementation/monolithic.md

  - 模块细节:
    - modules/index.md
    - Starry Core模块: modules/core.md
    - 系统调用模块: modules/syscall.md
    - UserPtr 封装: modules/userptr.md
    - 宏内核进程管理: modules/process.md

  - ArceOS 模块细节:
    - arceos-modules/index.md
    - 运行时模块:
      - arceos-modules/runtime/index.md
    - 硬件抽象层模块:
      - arceos-modules/hal/index.md
      - 模块接口与用例: arceos-modules/network/api.md
      - 自定义平台细节实现: arceos-modules/hal/customization.md
    - 动态内存分配模块:
      - arceos-modules/alloc/index.md
      - 模块接口与用例: arceos-modules/alloc/api.md
    - 驱动模块:
      - arceos-modules/driver/index.md
      - 驱动支持: arceos-modules/driver/support.md
      - 驱动总线支持: arceos-modules/driver/bus.md
    - 任务调度模块:
      - arceos-modules/task/index.md
      - 模块接口与用例: arceos-modules/task/api.md
      - 调度机制实现: arceos-modules/task/schedule.md
      - 多核调度支持: arceos-modules/task/multicore.md
    - 网络模块:
      - arceos-modules/network/index.md
      - 模块接口与用例: arceos-modules/network/api.md
      - 网络栈支持: arceos-modules/network/support.md
    - 文件系统模块:
      - arceos-modules/fs/index.md
      - 模块接口与用例: arceos-modules/fs/api.md
      - 文件系统兼容层: arceos-modules/fs/vfs.md
    - 虚拟内存管理模块:
      - arceos-modules/memory/index.md
      - 模块接口与用例: arceos-modules/memory/api.md
      - 内存管理机制: arceos-modules/memory/management.md
    - 命名空间模块:
      - arceos-modules/ns/index.md
      - arceos-modules/ns/management.md
      - arceos-modules/ns/api.md
    
  - 开发规划:
    - roadmap/index.md

  - 真实硬件平台开发:
    - hardware/index.md
    - x86 PC支持: hardware/x86-pc.md
    - 星光二代支持: hardware/sifive.md
    - 飞腾派支持: hardware/phytium.md
    - 树莓派支持: hardware/raspberry.md

  - 附录:
    - appendix/index.md
    - qemu-user 运行调试: appendix/qemu-user.md

  - 关于文档:
    - notes/index.md
    - 读者须知: notes/reader.md
    - 编辑者须知: notes/editor.md